targets:
  $default:
    builders:
      degen:
        enabled: true

builders:
  degen:
    import: "package:flutter_degen/build.dart"
    builder_factories: [ "degenBuilder" ]
    build_extensions: { ".dart": [ ".degen.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]

