name: flutter_degen
description: The Flutter code generator for your delegates
version: 0.4.4
homepage: https://github.com/ericmartineau/flutter_degen
repository: https://github.com/ericmartineau/flutter_degen
documentation: https://github.com/ericmartineau/flutter_degen
issue_tracker: https://github.com/ericmartineau/flutter_degen/issues
authors:
  - Eric Martineau <eric@sunnyapp.co>

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  fluttergen: flutter_degen_command

dependencies:
  build_runner: ^1.10.1
  source_gen:
  build_config:
  analyzer:
  build: ^1.3.0
  flutter_degen_annotations:
  args: ^1.6.0
  path: ^1.7.0
  yaml: ^2.2.1
  mime: ^0.9.7
  xml: ^4.2.0
  dart_style: ^1.3.6
  dartx: ^0.5.0
  color: ^2.1.1

dev_dependencies:
  test:
  test_coverage:
  effective_dart:
  build_test:
