name: example

dependencies:
  flutter_degen_annotations:

dev_dependencies:
  flutter_degen:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/chip3/chip3.jpg
    - assets/images/chip3/chip3.jpg # duplicated
    - assets/images/chip4/
    - assets/images/icons/fuchsia.svg
    - assets/images/icons/kmm.svg
    - assets/images/icons/paint.svg
    - assets/json/fruits.json
    - pictures/chip5.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

    # duplicated
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

